POST http://localhost:3333/videos
Content-type: application/json

{
  "title": "My first video",
  "description": "This is my first video upload",
  "duration": 120
}

###

GET http://localhost:3333/videos?search=test

###

PUT http://localhost:3333/videos/f9d0f3fc-a42a-4c5d-ae9f-97f7d7e2a178
Content-type: application/json

{
  "title": "TEST TEST",
  "description": "This is my first video upload",
  "duration": 120
}

###

DELETE http://localhost:3333/videos/a940b456-474f-4e43-b01e-fd38908d3021
